### ISSUE TITLE
STMをクライアントとするTCP接続テストの動作確認

### ISSUE THREAD

**Issue by ken551** [mROS-base/mros2-asp3-f767zi#14]
tcp2, tcp8がlinux環境下でnetcatを用いた場合の動作確認ができていない

デバッガで接続して、`sample_lwip_scene2`の頭にブレークポイントを挟むと正しく動作する

**Comment by takasehideki** [comment]
これコード再構成のために現状では再現させられないので，いったんcloseとします．
